name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      - name: Build static site
        run: |
          mkdir -p public
          cp index.html public/
          cp -r css public/
          cp -r js public/
          cp -r assets public/
          cp CNAME public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
